### ISSUE TITLE
TMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by msh940620** [CocoaLumberjack/CocoaLumberjack#1097]
ITMS-90338: Non-public API usage:
ddSetLogLevel:, 

in: DDLog.h
```
@property (class, nonatomic, readwrite, setter=ddSetLogLevel:) DDLogLevel ddLogLevel;
```
in: DDLog.m
```
SEL setterSel = @selector(ddSetLogLevel:);    line:537
[aClass ddSetLogLevel:level];    line:679
```

**Comment by geemaple** [comment]
Same rejection: ITMS-90338: Non-public API usage 
"Registered Dynamic Logging" part use this api

**Comment by mikemuzza** [comment]
Also seeing this issue:

> ITMS-90338: Non-public API usage - The app references non-public selectors in Ideate: _canPerformAction:forCell:sender:, _performAction:forCell:sender:, _tableView, _titleForHeaderInSection:, ddSetLogLevel:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by mikemuzza** [comment]
I actually found that my issue was related to another library: Flex. 

I'm guessing this CocoaLumberjack method `ddSetLogLevel:` is somehow getting called from the other private methods? Not sure, but seems like it's not really CocoaLumberjack's issue directly.

**Comment by litaifu** [comment]
ITMS-90338: Non-public API usage - The app references non-public selectors in : _postCacheModelChangedNotification, databasePool:didAddDatabase:, databasePool:shouldAddDatabaseToPool:, ddSetLogLevel:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by ckrey** [comment]
<img width="703" alt="Screenshot 2020-01-17 at 17 53 52" src="https://user-images.githubusercontent.com/4027289/72630307-5ab2f300-3952-11ea-8e30-ba269cef0b87.png">

**Comment by ffried** [comment]
Sorry for the late reply. This seems to be an issue that becomes more and more relevant. I'm not sure what we can do really. About `ddSetLogLevel:` I could imagine renaming it to `setDDLogLevel:`. But `didLogMessage` and `willLogMessage` is clearly not something Apple should be flagging. These are way to generic selectors.

Are any of you guys getting rejections because of this? Or is this only a warning for now?
In either case, I think it would make sense if you could just pass on the feedback to Apple that these selectors are too generic to be included in their flagging.


@CocoaLumberjack/collaborators Is there anything else we can do about this? Do we have any contacts at Apple?

**Comment by lolgear** [comment]
According to `didLogMessage `, we could add additional parameter:

```
- logger:didLogMessage:
```

or even

```
- ddLogger:willLogMessage:
```

**Comment by ffried** [comment]
@lolgear Yea, but since these would all be breaking changes, we'd have to maintain backwards compatibility. By doing so, we'd still have the old selectors in our framework.

I've already started a patch for `setDDLogLevel:`, where I'm breaking up the old selector name so that Apple won't be able to simply detect it. I wouldn't care if it's one selector we'd have to treat this way. But if we continue this, we'll soon only have "uglified" selector names in our code.

Given that `ddSetLogLevel:` was flagged by Apple, I'm not sure adding `ddLogger:` as parameter will do much good, since apparently Apple is using the 'DD' prefix as well somewhere.
And with `logger:didLogMessage:` it's only a matter of time until Apple's code also does something similar...

**Comment by lolgear** [comment]
@ffried 

Let's do it radically and choose another prefix. I vote for

```
CCLMBRJCK
```

**Comment by lolgear** [comment]
> it's only a matter of time until Apple's code also does something similar...
Dreadful...

**Comment by ksuther** [comment]
Apple is using CocoaLumberjack in their own private frameworks which triggers this false positive.

```
/System/Library/PrivateFrameworks/HTTPServer.framework/Versions/A/HTTPServer
/System/Library/PrivateFrameworks/WebDriver.framework/Versions/A/WebDriver
```

If you are actually rejected for this, point this out to them in the resolution center.

I wouldn't recommend going down the road of trying to rename symbols, as that's just kicking the can down the road for when Apple pulls the new symbols into those private frameworks.

**Comment by ffried** [comment]
@ksuther Good point, thanks! Didn't consider that... In that case their detection system is more flawed than I thought. And yes, renaming symbols is no help then.

In this case, there's nothing we can and should do here apart from pointing this out to Apple in case an app is rejected.

I'm closing this issue. If rejections should become more frequent, we could consider adding a note to the README.
