### ISSUE TITLE
NS_ASSUME_NONNULL_BEGIN with (NSString *)createNewLogFile

### ISSUE THREAD

**Issue by Mark-Collette-Connected** [CocoaLumberjack/CocoaLumberjack#1103]
https://github.com/CocoaLumberjack/CocoaLumberjack/blob/ded5f5999c853e7fef61fc27db100b169db0e21f/Sources/CocoaLumberjack/include/DDFileLogger.h#L151

createNewLogFile can return nil, as it's signature seems to confirm, but due to the `NS_ASSUME_NONNULL_BEGIN` wrapping the whole file, it bridges to Swift as `String` instead of its true behaviour of `String?`, which can cause a crash when the function returns nil.

**Comment by ffried** [comment]
@Mark-Collette-Connected You're right, there is actually a path now that could return `nil`. Although if we get there, something went wrong along the way. Did you actually encounter this?
Also, this is a method, that should only be called by the `DDFileLogger` instance using the manager, since otherwise it might log into the wrong file. If you want to manually create a new log file, you should use `rollLogFileWithCompletion:` on the `DDFileLogger`.

**Comment by Mark-Collette-Connected** [comment]
@ffried Yes, we have encountered this, and it's caused crashes in production when we overrode the function in a Swift sub-class that adds more logic to it.

**Comment by ffried** [comment]
@Mark-Collette-Connected Interesting. Do you have the NSLogs that went along with this? Again, if `createNewLogFile` returns `nil`, something quite fatal already happened (as in we couldn't create a new file in at least 5 attempts).

But I've made an attempt to deal with this as good as we can: #1111
