### ISSUE TITLE
'CLIColor.h' file not found

### ISSUE THREAD

**Issue by chrisballinger** [CocoaLumberjack/CocoaLumberjack#1105]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 CocoaLumberjack Version | 3.6.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.1

### Issue Description and Steps

When integrating CocoaLumberjack with the following experimental CocoaPods options, the `CLIColor.h` file is not found in the generated umbrella header. Specifically this affects other Pods that depend on CocoaLumberjack.

```ruby
# Podfile
install! 'cocoapods', :generate_multiple_pod_projects => true
```

If `generate_multiple_pod_projects` is set to false, it compiles as expected.

**Comment by ffried** [comment]
@chrisballinger I think this might be an issue with CocoaPods. I've checked our PodSpec and we don't do any conditional checks on our sources/headers. Also, the umbrella header we provide includes the `CLIColor.h` header [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/Supporting%20Files/CocoaLumberjack.h#L98).

Or is there anything we'd have to do in a special way to support this option? If it's experimental, though, I'm not sure whether we should support it if it requires changes on our side. 🤔

**Comment by lolgear** [comment]
> If it's experimental

[License](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/LICENSE)

No warranty :)

**Comment by sushichop** [comment]
@chrisballinger 
Thanks for reporting your issue. 
Unfortunately I could not repro it... I used **CocoaPods 1.8.2**. 
`CocoaLumberjack-umbrella.h` was generated and it seems to include `#import "CLIColor.h"`.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 CocoaLumberjack Version | 3.6.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.1
 CocoaPods Version           | 1.8.3

Podfile is as follows.
```ruby
install! 'cocoapods', :generate_multiple_pod_projects => true
inhibit_all_warnings!

target 'CocoaLumberjackSample' do
  use_frameworks!
  platform :osx, '10.12'
  pod 'CocoaLumberjack', '3.6.0'
end
```

Even if you use CocoaPods 1.8.2, does this issue still occur?

**Comment by chrisballinger** [comment]
It might be a CocoaPods issue. I was also not using `use_frameworks!`, instead I was using `use_modular_headers!`

The issues were also coming from Pods that depended on CocoaLumberjack, not the main target. Try also including another Pod like `LumberjackConsole`

```ruby
install! 'cocoapods', :generate_multiple_pod_projects => true
inhibit_all_warnings!

target 'CocoaLumberjackSample' do
  use_modular_headers!
  platform :osx, '10.12'
  
  pod 'CocoaLumberjack', '3.6.0'
  pod 'LumberjackConsole'
end
```

**Comment by chrisballinger** [comment]
It may indeed be a CocoaPods issue, but this oddity didn't affect any of the other pods I had integrated, so it may be possible to work around it with a small change... somewhere.

**Comment by sushichop** [comment]
> ```ruby
> install! 'cocoapods', :generate_multiple_pod_projects => true
> inhibit_all_warnings!
> 
> target 'CocoaLumberjackSample' do
>   use_modular_headers!
>   platform :osx, '10.12'
>   
>   pod 'CocoaLumberjack', '3.6.0'
>   pod 'LumberjackConsole'
> end
> ```

I tried the above and I got the following error message when I executed `pod install`.

```
[!] The platform of the target `CocoaLumberjackObjC2019103002` (macOS 10.12) is not compatible with `LumberjackConsole (3.3.1)`, which does not support `macOS`.
```

You can import `CLIColor.h` of CocoaLumberjack only when your app's target is macOS. See [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Sources/CocoaLumberjack/include/CLIColor.h#L16).
On the other hand [LumberjackConsole](https://github.com/PTEz/LumberjackConsole) supports only iOS 5.0 or later.
That's why you can not import `CLIColor.h` unfortunately.

**Comment by sushichop** [comment]
@chrisballinger 
I also tried above and looked into `CocoaLumberjack` a little.
Then I confirmed `CLIColor not found` because it is not public when platform is iOS including Mac Catalyst...

But IMHO you do not need to use CLIColor directly if you want to use the feature of color in CocoaLumberjack. Actually you need to use `UIColor` or `NSColor`. See [here](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeColors.md).
(So I think `CLIColor.h` should be set to internal-API now...🤔) 

On more thing, IMHO, colored feature of CocoaLumberjack is useful `only when` target app is macOS app unfortunately.
AFAIK it should depend on [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) and XcodeColors plugin does not work officially when Xcode version is 8.0 or later...

**Comment by chrisballinger** [comment]
@sushichop Thanks for the follow up! I'm not actually attempting to use CLIColor, just recompiling an iOS app for Catalyst. Not sure what the right fix is here, especially because it works with `:generate_multiple_pod_projects => false`.

**Comment by sushichop** [comment]
@chrisballinger 
I'm not sure, but multiple projects are generated in Pods project if you set `generate_multiple_pod_projects => true`. And you will see LumberjackConsole project's deployment target is iOS 5.0 or later. 
On the other hand, only h or m files are generated in Pods project if you set `generate_multiple_pod_projects => false`.

That's why you get the following error message, I think.

```
[!] The platform of the target `CocoaLumberjackObjCSampleApp` (macOS 10.12) is not compatible with `LumberjackConsole (3.3.1)`, which does not support `macOS`.
```

**Comment by sushichop** [comment]
@chrisballinger 
I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
My understanding about this issue is as above.
Please feel free to reopen it if you have any questions.

Thanks.
