### ISSUE TITLE
No console output after added DDFileLogger Swift 5.1 xcode 11.2

### ISSUE THREAD

**Issue by gkurpiel** [CocoaLumberjack/CocoaLumberjack#1112]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.2.2
 CocoaLumberjack Version | 3.6.0
 Integration Method      | carthage
 Xcode Version           |  Xcode 11.2
 Repro rate              | all the time (100%)
 Demo project link       | n.a.

### Issue Description and Steps

After upgrade my code to new xcode version and recompiled all used carthage frameworks i dont see any logs in the cosole. When i comment the filelogger part then it works. Someone has an idea?

```swift
    // File logger
    if AppConstants.USE_FEATURE_SEND_LOGS {
      let logManager = CustomDDFileManager()
      fileLogger = CustomDDFileLogger(logFileManager: logManager)
      if let fileLogger = fileLogger {
        fileLogger.rollingFrequency = -1
        fileLogger.logFileManager.maximumNumberOfLogFiles = 2
        DDLog.add(fileLogger)
      }
    }

    DDLog.add(DDTTYLogger.sharedInstance)
    DDLog.add(XCDLumberjackNSLogger())
```

**Comment by ffried** [comment]
@gkurpiel I've got two more questions / remarks for you:

- Have you tried to use the default `DDFileLogger` (and `DDDefaultLogFileManager`)? Just to be sure that your custom logger does not break anything.
- You should probably switch to `DDOSLogger` instead of `DDTTYLogger` since the latter is deprecated.

**Comment by gkurpiel** [comment]
Thanks alot for the hint... it seems my CustomDDFileLogger is the issue. Maybe you have an idea what could cause it or what i missed:
```
import Foundation
import CocoaLumberjackSwift

public final class CustomDDFileLogger: DDFileLogger {

  public override func willLogMessage(_ logFileInfo: DDLogFileInfo) {
    super.willLogMessage(logFileInfo)
  
    // Create a new logfile if the we are about to log and the next month starts.
    let lastLogCreationDate = currentLogFileInfo.creationDate
    let calendar = Calendar(identifier: .iso8601)
    if !calendar.isDate(lastLogCreationDate, equalTo: Date(), toGranularity: Calendar.Component.month) {
      rollLogFile(withCompletion: nil)
    }
  }
}
```

**Comment by gkurpiel** [comment]
I have found that this line is causing the issue: ```let lastLogCreationDate = currentLogFileInfo.creationDate``` . But i do not understand why.

**Comment by gkurpiel** [comment]
When i try to debug it the debugger is crashing and i get this in console:
(lldb) po currentLogFileInfo
Warning: hit breakpoint while running function, skipping commands and conditions to prevent recursion.

**Comment by ffried** [comment]
@gkurpiel I'm pretty sure you're running into a deadlock here. The `willLogMessage:` and `didLogMessage:` calls happen on an internal queue. Accessing `currentLogFileInfo` also locks that queue.

But this is why there is a parameter to `willLogMessage:` and `didLogMessage:`. Instead of accessing `currentLogFileInfo` you should just use the `logFileInfo` that is passed to those methods. This parameter actually _is_ the current log file info.

**Comment by gkurpiel** [comment]
Good idea but when i try to use the param directly then i get this error:
let lastLogCreationDate = logFileInfo.creationDate
-> Thread 3: EXC_BREAKPOINT (code=1, subcode=0x1f953da70)

**Comment by ffried** [comment]
@gkurpiel could be, because it's `nil` but not correctly annotated on our side. 🤔 
Try the following: `let lastLogCreationDate = logFileInfo.fileAttributes[FileAttributeKey.creationDate.rawValue] as? Date`

I'm preparing a PR which cleans up a few things here (e.g. the need for `FileAttributeKey.creationDate.rawValue` instead of just `.creationDate`).

**Comment by gkurpiel** [comment]
@ffried this solution is working for me.... thank you very much!!!!

**Comment by ffried** [comment]
@gkurpiel And you get a non-nil creation date?

**Comment by gkurpiel** [comment]
@ffried yes... shoud i not? ;-)

**Comment by ffried** [comment]
@gkurpiel Yes, sure. I'm just a little surprised now that you ran into the exception earlier, since we're actually doing the same when you access the `creationDate` property of the log file info. 🤔

**Comment by ffried** [comment]
@gkurpiel Took a little longer than expected, but #1111 also fixes the Swift annotations for `DDLogFileInfo`. After it's merged, you should first of all be able to access `logFileInfo.creationDate` directly, but also not need `.rawValue` anymore, when "manually" getting the creationDate: `let lastLogCreationDate = logFileInfo.fileAttributes[.creationDate] as? Date`.

**Comment by ffried** [comment]
Since #1111 is merged now, I'm closing this.
