### ISSUE TITLE
Public Domain - CocoaLumberjack-3.2.1.zip

### ISSUE THREAD

**Issue by phaupt** [CocoaLumberjack/CocoaLumberjack#1116]
Dear Creator

Would it be okay to use your work [CocoaLumberjack-3.2.1.zip] under Creative Commons CC0 v1.0 Universal License (CC0 v1.0)?

The Swiss law do not recognize a permanent relinquishment of Copyrights as the Public Domain provides for.

Thank you very much and kind regards
Philipp

**Comment by ffried** [comment]
@phaupt Disclaimer: I'm not in a position to make this decision. I think this would have to be clarified with @bpoplauschi and @rivera-ernesto, or possibly with @robbiehanson.

But I think we need some more information here - or at least I would if I were in a position to make this decision. 🙂 
Is there a specific issue with the BSD3 license CocoaLumberjack is currently using? According to the definition, a software enters the Public Domain as soon as its creator gives up the copyright - which, you're right, is not possible in Switzerland (https://ssa.ch/en/ssa-at-a-glance/on-copyright/).

But since the BSD3 license requires attribution of copyright, we shouldn't be affected by that, or am I missing something?

**Comment by bpoplauschi** [comment]
@ffried I have a similar understanding to what you wrote.
Decisions about the copyright can only be made by the owner of those rights @robbiehanson 
Unless someone talks to an attorney, I don't see that BSD3 license changing or being dropped, so the question for @phaupt is what / why do you need a different license for CL?

**Comment by phaupt** [comment]
Surely it should be a good thing when an author publishes their code in the public domain, giving the general public open access. However, while this might be the case in the USA, in the EU and Switzerland, it comes with certain problems, as the author cannot transfer their copyrights to the public domain. What is more, the public domain does not cover usage rights. The public domain is a good idea, but its usage is not legally secure in Switzerland, and it is the subject of controversial discussion. Some authors already avoid this dilemma by publishing their source code under the Creative Commons CC0 1.0 Universal Licence (CC0) if the public domain is not usable. The CCO follows the same mindset as the public domain, but without the legal issues. Of course, you could say, ‘I’ll just use the source code in the public domain anyway.’ However, there is always the danger that the author could change their mind at any time and place their code under an open source licence, which could, for example, prohibit the use of the code for commercial purposes. This can have direct consequences for the developed software. The dilemma can be solved by the author granting usage rights or by avoiding using the source code in software.

**Comment by ffried** [comment]
@phaupt Since we *do* have an open source license (BSD3) we are *not* part of the public domain. So all the problems you mentioned shouldn't really exist, right?

The problems you mentioned in the EU and in Switzerland arise when the author wants to *give up* its copyright. This is possible in the USA, but not as easy in the EU and CH where the copyright is protected even if the publisher does not explicitly do so. But given that CL does not give up its copyright, we (and you, if you want to use CL) are within the laws of EU and CH.

Or at least that's my understanding of the situation - but I'm no lawyer.

Btw. even if we were to change the BSD3 license in a future version, you'd still be permitted to use previous versions published under the current BSD3 license.

**Comment by bpoplauschi** [comment]
I agree with @ffried.
+ given that we are using the same BSD3 license for the past 9+ years, the author has stepped down from managing the project and us maintainers are not empowered to change the licensing, I think it's pretty safe to say this will remain the license for our project for a long time.
