### ISSUE TITLE
Log rotate has some problem in 3.7.4 version

### ISSUE THREAD

**Issue by oyljerry** [CocoaLumberjack/CocoaLumberjack#1276]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  osx
 Platform Version        | all
 CocoaLumberjack Version | 3.7.4
 Integration Method      | carthage
 Xcode Version           | Xcode 12.4
 Repro rate              | all the time (100%) 

### Issue Description and Steps

I have just upgraded CocoaLumberjack from 3.7.2 to 3.7.4, But I found there is some strange problems occur.

Below is code about how to control log rotate.

```
    fileLogger.maximumFileSize = 20 * 1024 * 1024;
    fileLogger.rollingFrequency = 0;
```

![image](https://user-images.githubusercontent.com/756387/148028901-b543163b-7b35-4301-a280-034a1d7ef620.png)

**Issuer#1:**

I found that the log is rotated when its size is only 1.3M, In 3.7.2, This works as 20M.

**Issuer#2:**

The log file which should be xxx-202112291336.log, but it has been changed to xxx-202212291336.log

**Is this issue related to https://github.com/CocoaLumberjack/CocoaLumberjack/pull/1234???**

**Comment by ffried** [comment]
Are you using a subclass of `DDLogFileManagerDefault`?
If so, I could see both issues coming from an incomplete implementation:

The default log file name uses the following pattern as log file name: "<app name> <date> <time>.log"
Since your format differs from that, you've likely overridden `-newLogFileName`. To solve your date issue, please have a look at the date formatter you are using there. Specifically take care to use `yyyy` not `YYYY` for the year.

Also, if you override `-newLogFileName`, you also need to properly implement `-isLogFile:`! Otherwise the log files won't be recognized by other (non-overridden) implementations of `DDLogFileManagerDefault` and thus might not be reused correctly, resulting in new log files even though the criteria for rolling hasn't yet been met.

**Comment by oyljerry** [comment]
Thanks @ffried  , The date format is wrong, I need to change from YYYY to yyyy.

**Comment by oyljerry** [comment]
@ffried :
After some testing, We found **issuer1** still happened in below scenario. Please help to check it. 

1. On 2022-01-06, start app, the log generated date is aaaa-202201061900.log, 
2. I shutdown my macOS at 2022-01-06 22:00
3. After 1 day, at 2022-01-07, I power on my macOS, start my app.
4. It will generate a new log, aaaa-202201071416.log, however, aaaa-202201061900.log size is 1.4MB
5. However, I have set **fileLogger.maximumFileSize = 20 * 1024 * 1024;**

Below is **newLogFileName** and **isLogFile** implementation.

```
- (NSString *)newLogFileName
{
    static dispatch_once_t onceToken;
    static NSDateFormatter *dateFormatter;
    dispatch_once(&onceToken, ^{
        dateFormatter = [NSDateFormatter new];
        [dateFormatter setDateFormat:@"yyyyMMddHHmm"];
    });
    NSString* date = [dateFormatter stringFromDate:NSDate.date];
    return [NSString stringWithFormat:@"%@-%@.log", @"aaaa", date];
}

- (BOOL)isLogFile:(NSString *)fileName
{
    NSLog(@"fileName = %@, %@", fileName, @"aaaa");
    return [fileName hasPrefix:@"aaaa"];
}
```

PS. This issue will not happen, If I do not restart my app, ex, I keep running my app from 20220107 to 20220110, It will generate three log files. The log module works as expectation.  
aaaa-202201070207.log   -> 21M
aaaa-202201081939.log  -> 21M
aaaa-202201101306.log   -> 6.6M

**Comment by ffried** [comment]
@oyljerry Can you try with the lastest state of `master`? There has been a change made in #1287 that _might_ resolve that problem.

**Comment by coolwuzizai** [comment]
@ffried hi,I meet this problem. when I use  pod 'CocoaLumberjack/Swift', '3.7.0',the swift project can rotate after 24 hours. But   pod 'CocoaLumberjack', '3.7.2' or '3.7.4',the objective c project cann't rotate after 24 hours. I don't know why. I just guess maybe dispatch_time? or different between dispatch_time and dispatch_walltime ? Could you give me some help or suggestion? thanks.

**Comment by coolwuzizai** [comment]
I do like oyljerry, but 
`fileLogger.maximumFileSize = 0;
        fileLogger.rollingFrequency = 60 * 60 * 24`,he rorate log by filesize,I want to rorate by hours. newLogFileName and isLogFile implementation also like him.

**Comment by coolwuzizai** [comment]
@oyljerry hi ,Could you give some advices or tell me how you fix it ?thank you very much.

**Comment by ffried** [comment]
@oyljerry @coolwuzizai I just went through all the changes since 3.7.0 and I really can't seem to figure out what's wrong.
I've just pushed a small change (cf6e7e0b2ebfe7cc741530fda03950284e9d28df) that _might_ fix some of this issue, but I'm not sure it's the root of the evil.
I'd still be very happy to have a small reproduction project on my hands - best with a small rolling interval to easily reproduce it w/o having to wait a day 😉 

Could you guys give `master` a test (with my latest commit) to see if anything changes?

**Comment by coolwuzizai** [comment]
> 

@ffried thanks,I will test for the master. oh,I remember something,when I set fileLogger.rollingFrequency = 60 * 3 (test for three minutes or ten minutes，it works ! But when set  60 * 60 * 24, cann't rotate ,so I guess the dispatch_time because dispatch_time will stop when computer is sleep).   But if I restart the app after rollingFrequency, it sometimes create a new LogFile.

**Comment by coolwuzizai** [comment]
@ffried hi,I find a problem 16 days ago the old version.  I set  fileLogger.maximumFileSize = 50 * 1024 * 1024;
    fileLogger.rollingFrequency = 0; But it will roll about 25 hours. I know this could because dispatch_time, but why this Log rotate use 24hours not maximumFileSize. So fantasy!  I will load the new code to see this if I have time, thanks

**Comment by OrrHsiao** [comment]
I found the same problem with version 3.8.1,this is my configuration,but in reality, every time you reopen the app, it generates a new file.
`    DDFileLogger *fileLogger = [[DDFileLogger alloc] init];
    fileLogger.doNotReuseLogFiles = NO;
    fileLogger.rollingFrequency = 60 * 60 * 24;
    fileLogger.maximumFileSize = 15 * 1024 * 1024;
    fileLogger.logFileManager.logFilesDiskQuota = 1024 * 1024 * 500;
    [DDLog addLogger:fileLogger withLevel:level];
`

**Comment by ffried** [comment]
Can you guys try the latest `master` branch? #1357 is another candidate that might fix this.

**Comment by OrrHsiao** [comment]
> Can you guys try the latest `master` branch? #1357 is another candidate that might fix this.

I use the latest master code and this problem no longer occurs, thanks😊

**Comment by ffried** [comment]
Thanks for confirming. Then this is finally fixed.
