### ISSUE TITLE
Crash ! why ?

### ISSUE THREAD

**Issue by Goallying** [CocoaLumberjack/CocoaLumberjack#1291]
![c25412f76258032db29b8f324ba5a65c](https://user-images.githubusercontent.com/12438493/154183015-ce587202-81fc-40b9-8732-14001d126107.png)

**Comment by ffried** [comment]
The issue here is that you have two placeholders (`%@`) in your format string, but only one argument in the list.
In the stack trace you should see where this call is coming from and there you need to either pass another argument, or remove one `%@` from your format string.

**Comment by Goallying** [comment]
sorry, I'm not familiar with "va_list" ,how did you know there was only one argument in the list ? I didn't recognized it, can you figure it out  for me ?

**Comment by ffried** [comment]
@Goallying Ah, sorry - missed the type in the debug output. Yea, `va_list`s are quite terrible to debug. Either way, the issue is still somewhere within the format string / arguments.

To proof that, try the following in the place where you call `DDLogInfo` today:
```objc
NSString *message = [[NSString alloc] initWithFormat: @"蓝牙框架 - 数据解析 %@ 开始分发 当前分发队列 %@", cmdStr, self.writeServiceCallBackList];
DDLogInfo(@"%@", message);
```

If it crashes in the line where you create message, it's unrelated to CocoaLumberjack...
Also, if you step over the crash, you should get some information from the exception that is thrown.
