### ISSUE TITLE
时间有问题怎么解决？

### ISSUE THREAD

**Issue by chengssir** [CocoaLumberjack/CocoaLumberjack#1331]
2023/02/22 00:53:41:670  app logger:CHAT_MSG_CLICK, paramter:Optiona
2023/02/22 00:53:41:680  app logger:CHAT_MSG_CLICK, paramter:Optiona

两个打点实际上是用户点击空间的日志，理论不可能存在两个数据的时间相差的这么近?
但是在日志库数据里两个时间相差毫秒级的

**Comment by ffried** [comment]
I don't really see an issue with CocoaLumberjack here, so I'm closing this.

There are many reasons for those log statements to have a timestamp so close to each other:

- On macOS it's completely possible to perform a double click within less than a second. Possibly this is the same on iOS.
- The log formatter might use the wrong / current date instead of the one of the log message.
- The log message is triggered twice (e.g. copy/paste mistake).
- The timestamps aren't actually from the log message, but are added by e.g. `os_log`.
- ...

If you feel this is actually a problem in CocoaLumberjack, please re-open this issue and provide further details on when exactly this happens and why it's an issue with CocoaLumberjack. A small reproduction project would for example be perfect.
