### ISSUE TITLE
preserve the format string as an attribute on DDLogMessage

### ISSUE THREAD

**Issue by mmerickel** [CocoaLumberjack/CocoaLumberjack#1346]
**Is your feature request related to a problem? Please describe.**

We have our log system connected to sentry such that error messages trigger sentry events and lower messages create sentry breadcrumbs. Sentry has a feature where you can pass the un-interpolated format string to it, so that it can intelligently deduplicate messages. Without it, each message tends to create a new event because the interpolated string contains new data each time.

**Describe the solution you'd like**

Add a new attribute to the `DDLogMessage` to track the `rawLogMsg` or something. When `[DDLog log: ... format:]` is invoked, store the `format` argument there. If one of the APIs that doesn't not take a format is used, then just store the formatted message there, or make it nullable.

**Describe alternatives you've considered**

It could be possible for me to framework something ourselves around the macros to marshal an `NSDictionary` in the `tag` attribute. However I think it makes sense just as a builtin feature which is why I'm raising this use case here.

For context here is the `SentryMessage` object where we are interested in filling in the `message` attribute. Potentially `params` would be nice too, but I'm leaving this out of the request due to the possible performance concerns and/or race conditions around preserving the va_list args. The unformatted message itself is already an immutable `NSString *` once it hits `DDLog` so this request is just to keep a handle to it on `DDLogMessage` for a logger to use later.

https://github.com/getsentry/sentry-cocoa/blob/596ccc1396714bd5d6daa893912a008d94ba8c10/Sources/Sentry/Public/SentryMessage.h#L32-L37

**Comment by ffried** [comment]
@mmerickel First of all, thank you for a very thought-out and well-written feature request!
I've given this a shot in #1347. The Objective-C part was more or less easy. Had to do a bit more work for the Swift overlay to get the format (Swift has string interpolation, so no more format strings).

Persisting the format arguments is - even if we would do this - impossible at the moment. At least I haven't found a reliable way of getting e.g. an `NSArray` from a `va_list`. Given that the latter is basically just continuous memory (on most ABIs), you *need* to know the stored types to reliably extract the values. And since not all of the arguments might be objects (`id`), but also contains e.g. primitives (`int`, `double`, ...), we also cannot simply extract all of them as objects.

This is where the Swift implementation is more powerful. But it didn't really make sense to me to only provide this for Swift-created messages. Especially since our `swift-log` handler isn't able to do this, either.

**Comment by mmerickel** [comment]
Wow, nice work. That was quick! You're right about the va_list issue which is another reason to not store it. As I said initially as well I think it'd be opening up some weird race conditions as well because there's probably code that doesn't want those args passed to another thread where DDLogMessage ends up being handled by a logger.
