### ISSUE TITLE
isRegisteredClass in iOS 17 simulator kills UserDefauls functionality

### ISSUE THREAD

**Issue by cmdrsabre** [CocoaLumberjack/CocoaLumberjack#1386]
In Issue #24 there was a junction made to have non-IOS Code run in the simulator to prevent a crash.
Now with iOS 17 the non-IOS code in the Simulator part does have some weird issues!
UserDefaults stop working!

The real iPhone Code does work!

So the current version does not work on iOS 17 simulators (or at least UserDefaults do not work after calling)

_Originally posted by @cmdrsabre in https://github.com/CocoaLumberjack/CocoaLumberjack/issues/24#issuecomment-1759648790_

**Comment by cweymann** [comment]
Hi, First of all thank you for all your hard work!

I think while fixing this issue there was an unintended consequence. While the simulator does behave correclty with 3.8.2 the real device now has issues with using UserDefaults. This seems to be because on an iOS device does not return when running through the special iOS code but goes through the non-iOS code as well before returning. 

I've created a patch to fix this and improve readability, but it might have a negative performance impact, maybe there is a better way.  [patch.diff.txt](https://github.com/CocoaLumberjack/CocoaLumberjack/files/13845041/patch.diff.txt)

Still no idea why setting these selectors causes issues with the Userdefaults, but the problem is 100% reproducible in our setup. Also noticed that there seems to be a difference between release and debug builds. The issue does only occur with debug builds.

Hope this helps

**Comment by ffried** [comment]
@cweymann Sorry bout that! I did miss adding a return in the iOS 17 branch. I also added a further preprocessor conditional to make sure only relevant code is compiled.
