### ISSUE TITLE
The `dynamicLogLevel` isn't taken in account when using `swift-log`

### ISSUE THREAD

**Issue by bvirlet** [CocoaLumberjack/CocoaLumberjack#1390]
Hello,

We have been using `CocoaLumberjack` with `dynamicLogLevel` for years with standard `DDLogDebug`, `DDLogInfo` statements, and this has been working well. Thanks!

We're trying to introduce `swift-log` in our code base, and it seems it's ignoring the dynamic log level: `swift-log` loggers are initialized with a default `swift-log` log level of `info` (which can be changed with  `LoggingSystem.bootstrapWithCocoaLumberjack(defaultLogLevel: .debug)`, but it doesn't seem that it will take in account the dynamic log level.

The reason is that the dynamic log level is checked in `_DDLogMessage` and the `swift-log` handler doesn't go through that method but directly logs using the shared `DDLog` instance.

I have found that I could take the dynamic log level in account like so, but is this an acceptable implementation (and if so, why isn't `dynamicLogLevel` checked in `DDLog`'s `log` method rather than in `_DDLogMessage`?)

```swift
class DDSwiftLogLog: DDLog {
    override func log(asynchronous: Bool, message logMessage: DDLogMessage) {
        guard logMessage.level.rawValue & logMessage.flag.rawValue != 0 && CocoaLumberjackSwift.dynamicLogLevel.rawValue & logMessage.flag.rawValue != 0 else {
            return
        }
        DDLog.sharedInstance.log(asynchronous: asynchronous, message: logMessage)
    }
}

LoggingSystem.bootstrapWithCocoaLumberjack(for: DDSwiftLogLog(), defaultLogLevel: .debug)
```

What is your recommendation? 

Thanks!
Bruno

**Comment by ffried** [comment]
First of all thanks for a well-written issue, that clearly describes the problem and the solution you're looking for!

The reason for this is that the swift-log backend (`CocoaLumberjackSwiftLogBackend`) intentionally is a completely separate target from `CocoaLumberjackSwift` - and the latter has the `dynamicLogLevel` feature.
Both targets offer a different kind of "frontend" to the Objective-C target `CocoaLumberjack`.

[`swift-log` states](https://github.com/apple/swift-log?tab=readme-ov-file#not-under-control-of-loghandlers), that whether log messages are logged or not should normally not be under the control of a log handler:
<img width="868" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/0e3ad579-3fb1-4d2e-8e92-7943ee805404">

This is why we don't have something like `dynamicLogLevel` in our log handler. The `dynamicLogLevel` is basically the equivalent of `swift-log`'s `Logger.logLevel` property. Since `CocoaLumberjackSwift` does not have a `Logger` object, the `dynamicLogLevel` resides on the top level.

As for what I'd recommend:

Use `dynamicLogLevel` for usages with the `DDLogXYZ` functions only. If you need to filter log messages later on, you could e.g. configure your `DDLogger`s with a `DDLogFormatter` that simply returns nil for messages below (or above for that matter) a certain level. This results in the log message not being logged.

Another option would be what you already started: To use a subclass of `DDLog` and filter the messages there. I'd just recommend _not_ to use `dynamicLogLevel` for filtering here, but instead add your own property for a global log level.

In both cases: make sure you do protect this "global" log level correctly against concurrent access! 
Btw. this is an issue that `dynamicLogLevel` has at the moment: It's not actually protected against concurrent modification.

**Comment by bvirlet** [comment]
Thanks @ffried for the detailed response, I really appreciate.

We've been using `dynamicLogLevel` to have a "Debug log" toggle in the app so that we can get debug logs if needed from our users. So I need the debug log toggle to toggle a global state, and it should now affect both `DDLogXYZ` functions and the `swift-log`'s loggers (we are progressively introducing swift-log). I'm already using a user defaults as this global state (when it's changed, it changes `dynamicLogLevel`), so I could read this user default in my `DDLog` subclass instead of reading `dynamicLogLevel`.

**Comment by ffried** [comment]
That sounds like a good solution. `UserDefaults` should be thread-safe as well.
