### ISSUE TITLE
DDOSLogger Info, Warning, Debug, and Verbose logs do not appear in Console.app when streaming from iOS simulator.

### ISSUE THREAD

**Issue by jaredsinclair** [CocoaLumberjack/CocoaLumberjack#1409]
## Checklist

- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

## Description

DDOSLogger Info, Warning, Debug, and Verbose logs do not appear in Console.app when streaming from iOS simulator.

## Steps To Reproduce

1. Implement a log message (via Swift or Objective-C, it doesn't matter) using DDOSLogger via any method that uses a DDLogFlag value of `.info`, `.debug`, .`warning`, or `.verbose`. 
2. Run that statement on an iOS or iPadOS simulator while streaming logs to Console.app on the same Mac.
3. These log messages do not appear even when Info and Debug logs are enabled in Console.app.

## Expected behavior

Every log message sent to CocoaLumberjack should appear in Console.app when Info and Debug logs are enabled in Console.app, even when streaming from the iOS simulator.

**Environment info**
  Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | any Simulator device
 Platform Version        | at least as far back as iOS 16-17, probably before that, too
 CocoaLumberjack Version | latest
 Integration Method      | spm
 Xcode Version           | e.g. Xcode 15+
 Repro rate              | all the time
 Repro project link      | n/a

## Additional Context

Ultimately this is an Apple bug. The bug dates back [years and years](https://developer.apple.com/forums/thread/82736?page=2). However CocoaLumberjack should be aware of a longstanding bug like that and provide an automatic workaround that doesn't require end users to discover this shortcoming the hard way.

Specifically, [this switch statement in DDOSLogger](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/af4973721172dd7850a42a58a9ffcec0ec82e5a9/Sources/CocoaLumberjack/DDOSLogger.m#L105-L113) needs to be rethought:

```objc
switch (logMessage->_flag) {
    case DDLogFlagError  :
        os_log_error(logger, "%{public}s", msg);
        break;
    case DDLogFlagWarning:
    case DDLogFlagInfo   :
        os_log_info(logger, "%{public}s", msg);
        break;
    case DDLogFlagDebug  :
    case DDLogFlagVerbose:
    default              :
        os_log_debug(logger, "%{public}s", msg);
        break;
}
```

## Recommendations

The following changes should be made:

1. **All Devices:** `Warning` logs should never be downgraded to `os_log_info(...)`, they should be sent at the default: `os_log(...)`. This is true both for simulator and non-simulator target devices. OSLogType.info has special characteristics that make it unsuitable for use with warning-level logs (the characteristics of info logs are best described in the WWDC presentation the first year that Unified Logging was introduced).

2. **Simulators:** When running against a simulator, Info, Debug, and Verbose logs should be upgraded as if they had been logged at Warning, so that they can actually appear in the Console.app when streamed from the simulator. This workaround can be removed if Apple ever addresses it, but since the bug has existed for at least five years, there's seemingly little chance of that ever happening.

## Alternatives Considered

Given the current implementation of DDOSLogger, the only workaround for existing consumers is to roll their own upgrade, lifting all affected log statements streaming from a Simulator up to an Error log level. This is not an acceptable workaround, however, since Error logs also have a special treatment in log systems (not just in Console.app/Unified Logging). This workaround also puts a big burden on consumers because they would have to edit every call site that logs via `DDLogInfo(...)` etc. It would be far less invasive to surgically edit the implementation of DDOSLogger to implement a targeted workaround that only affects simulator builds, leaving all call sites intact.

**Comment by ffried** [comment]
First of all thanks for taking the time to describe everything in detail, including recommendations!

## Downgrade of Warning to Info

You're right that this is incorrect! They should be upgraded to error, which is what the [`.warning` function on `Logger` in `OSLog` does as well](https://developer.apple.com/documentation/os/logger/3551625-warning): 
<img width="544" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/6d1627ad-459b-4ecb-97aa-9b2030e35482">


## Missing messages in Console.app

I'm a bit torn here...
Reading a bit further in the forum you linked, I found [this answer by Quinn](https://developer.apple.com/forums/thread/82736?answerId=761544022#761544022).
Using CocoaLumberjack version 3.8.4, I was able to reproduce his findings:
Everything logged with `.info` or above is visible in Console.app:
<img width="309" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/4c470285-b681-4538-a6c2-ef0e8bb7ade9">
<img width="604" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/02985ed9-def4-41e0-830d-5a7c4d79a680">

This lines up with `.debug` messages not being shown, which was also classified as bug by Quinn in the forums.
Also matching Quinn's findings, I'm able to see these messages when using the Terminal:
<img width="1064" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/5348babb-f732-4f63-86c9-f108b1c70a1a">

Last but not least, I see all messages in Xcode's Console as well (Xcode 15.2):
<img width="259" alt="image" src="https://github.com/CocoaLumberjack/CocoaLumberjack/assets/1689782/5a767005-f7a7-412a-87d1-839767ec0015">



Long story short, I don't think it's that simple to add a workaround in CocoaLumberjack.
In its current form, the bug seems to only affect the Console.app, not the logging SDK itself.
Personally, I've never used the Console.app to read Simulator logs, though I can see that it might be helpful to see other logs (not only the application's logs).
Given that all log messages show up correctly in Xcode, we shouldn't generally raise `.debug` logs to a higher level.

I could imagine adding a "level mapper" of sorts to `DDOSLogger`, though. This could be used to map our log levels to the ones of OSLog. We'd then provide two default implementations: 
- One that basically does what the current implantation does.
- One that's only available when building for Simulator, that raises `.debug` to either `.default` or `.info`.
Users of CocoaLumberjack would then still need to add a little more code, but not implement the whole workaround themselves.

What do you think?

**Comment by jaredsinclair** [comment]
> You're right that this is incorrect! [Warning logs] should be upgraded to error

I left something out from my description. I've noticed that off-the-shelf there is not `DDLogMessage()` or `DDLog()` etc method that logs at a neutral level equivalent with `os_log(...)` (the default OSLogType). If Warning logs get upgraded to Error, then there's still no way to produce a log that is higher than a debug/info but not an error.

**Comment by jaredsinclair** [comment]
> I could imagine adding a "level mapper" of sorts to DDOSLogger, though

I think this idea is interesting. I've worked on projects where logging requirements change as different platform teams become subject to belated cross-platform logging standards. These standards can force teams to raise or lower log levels across the board, which can potentially wreak havoc on a codebase as thousands of log statements have to be audited to raise or lower the level to the new standard. It would be far easier to define a level mapping in one place, and leave call sites and team-specific logging practices untouched.

**Comment by ffried** [comment]
> I've noticed that off-the-shelf there is not a neutral DDLogMessage() or DDLog() or DDLogDefault() etc method that logs at a neutral level equivalent with os_log(...) (OSLogType .default).

That's due to CocoaLumberjack not having a 'neutral' log level. To be honest, I haven't really understood the concept of a 'neutral' log level - and have often seen it being overused if there was one.
FWIW, I've changed the `default` in the switch to use the `OS_LOG_TYPE_DEFAULT` in #1410.

> I think this idea is interesting.

Feel free to have a look at #1410 and see if the solution I've implemented there would fit your needs.
