### ISSUE TITLE
2.0rc not logging ?

### ISSUE THREAD

**Issue by JanC** [CocoaLumberjack/CocoaLumberjack#427]
Hi,
I don't know what I'm doing wrong but Lumberjack will just not log any of my statements.

My pch looks like this:

```objc
#import <CocoaLumberjack/CocoaLumberjack.h>

#if DEBUG
static const int ddLogLevel = DDLogLevelDebug;
#else
static const int ddLogLevel = DDLogLevelWarning;
#endif
```

App delegate:

```objc
    [DDLog addLogger:[DDASLLogger sharedInstance]];
    [DDLog addLogger:[DDTTYLogger sharedInstance]];
```

When I call this, nothing happens
```objc
DDLogDebug(@"Received HTTP %ld", (long) httpResponse.statusCode);
```

what am I doing wrong?

cheers

**Comment by rivera-ernesto** [comment]
I think loggers are shared all over the app. Maybe the log levels are set to off in the framework?

**Comment by JanC** [comment]
Have a look at the sample app I posted. I enable the logs in the app delegate but it's not working in the Framework.

**Comment by JanC** [comment]
Hi,
any update on this?

**Comment by bpoplauschi** [comment]
@JanC let me check, I will do this later today.

**Comment by rivera-ernesto** [comment]
A demo app or naming the names of the libraries not logging would help to nail down the problem.

**Comment by JanC** [comment]
I linked a demo app in my second post :)

**Comment by guidomb** [comment]
I am having a similar problem but with a simpler project. Newly created project just with CocoaLumberjack 2.0.0-rc and it does not log to XCode. Went back to 1.9.x and it worked.

I am using cocoapods 0.35.0

Here is my example project

https://dl.dropboxusercontent.com/u/4060090/Foo.zip

**Comment by rivera-ernesto** [comment]
May be fixed by #455.

**Comment by oshamsy** [comment]
@guidomb Change your ddLogLevel statements from:
#ifdef DEBUG
    static const int ddLogLevel = DDLogFlagVerbose;
#else
    static const int ddLogLevel = DDLogFlagWarning;
#endif

to 

#ifdef DEBUG
    static const DDLogLevel ddLogLevel = DDLogLevelVerbose;
#else
    static const DDLogLevel ddLogLevel = DDLogLevelWarning;
#endif

You need to use the logging levels here.

**Comment by oshamsy** [comment]
@JanC You have a conflict in your project settings. When I first ran your your app. I saw the following on the console:
`objc[33796]: Class DDTTYLoggerColorProfile is implemented in both /Users//xx/Library/Developer/Xcode/DerivedData/TestLog-gpksoitnthkwqvgcvhrdilenwwhl/Build/Products/Debug-iphonesimulator/TestLogKit.framework/TestLogKit and /Users/xx/Library/Developer/CoreSimulator/Devices/89F4B2AA-63CD-4077-8CF2-1440666965DC/data/Containers/Bundle/Application/F3495D05-C2DC-4662-8A79-F4E286CB8C84/TestLog.app/TestLog. One of the two will be used. Which one is undefined.`

This is because of how your project is structured and you have CocoaLumberjack specified in your Podfile for the TestLog target and the TestLogKit target.

To debug the problem I did a test which effectively removes the CocoaLumberjack pod from the TestLog app... since it is linked with the TestLogKit Framework. You can do the same thing to verify...

Do the following for the TestLog target:
1. In the Build Phases -> Link with Libraries: 
Remove  libPods-TestLog.a
2. in Build Settings -> Other Linker Flags
Remove  -l"Pods-TestLog-CocoaLumberjack"

Logging should now be working for the app and framework

**Comment by oshamsy** [comment]
@rivera-ernesto @bpoplauschi 
I think this can be closed.

**Comment by bpoplauschi** [comment]
Much appreciated @oshamsy

**Comment by rivera-ernesto** [comment]
@bpoplauschi Please could you release rc2?

**Comment by bpoplauschi** [comment]
@rivera-ernesto I will release it today.

**Comment by bpoplauschi** [comment]
Done, with a delay, but done

**Comment by rivera-ernesto** [comment]
Thanks a lot!
