### ISSUE TITLE
explicitly set log level when adding any logger is ignored / depends on defaultDebugLevel

### ISSUE THREAD

**Issue by vercruesse** [CocoaLumberjack/CocoaLumberjack#469]
Adding a logger as in the following example does not work as expected with 2.0.0-rc2

```swift
DDLog.addLogger(DDTTYLogger.sharedInstance(), withLevel: DDLogLevel.Info)
DDLogInfo("test")
```

Though the logger's level is set to .Info, there is no log output.

Setting the default log level global var makes the difference:

```swift
defaultDebugLevel = DDLogLevel.All // must be .Info at least to see the log output
DDLog.addLogger(DDTTYLogger.sharedInstance(), withLevel: DDLogLevel.Info)
DDLogInfo("test")
```

**Comment by bpoplauschi** [comment]
This sounds right to me. The global level must be set. The logger log level will only filter messages that pass the global level. The global level should be the most permissive of all the loggers' levels

**Comment by vercruesse** [comment]
I guess you are right. Just verified with CocoaLumberjack 1.9 and it also behaves the way you describe. I wrongly presumed that setting an explicit log level for a logger would overwrite the global default log level.

**Comment by rivera-ernesto** [comment]
I think that logically it should work the other way around. Probably the problem is that there is no "use default" log level to ignore the logger level and fallback to the global level.

**Comment by bpoplauschi** [comment]
I think this is a very debatable subject :) (since obviously we can discuss about it). For me, the global level says which log statements are active and which are ignored. Meaning that if I set the global level to **Info**, I do not care about **Debug** or **Verbose** logs. Then the logger log level can help say a certain logger doesn't need all the logs that were set globally (i.e. a logger to a 3rd party like Crashlytics should not carry over **Info** logs, just **Warn** and **Error**).
I can also understand @rivera-ernesto 's statement.  Ideally, one should be able to set a certain logger to a more permissive level. i.e. global level to **Info**, but the file logger could set the level to **Verbose** and therefore include all the logs.
Going into the current implementation details, I'm not sure how to implement this. Right now, the global log level will prevent some logs (with the level greater than the global level) from being sent to the loggers.

**Comment by johnryan** [comment]
@bpoplauschi Was there any resolution to this? Ideally i'd like to have something like this:
```
#ifdef DEBUG
static const int ddLogLevel = DDLogLevelVerbose;
#else
static const int ddLogLevel = DDLogLevelError;
#endif
```
So that the console log is clean in release builds....but to also have a verbose file logger. Am I understanding the last comment correctly that this is not possible?

**Comment by bpoplauschi** [comment]
@johnryan the code you posted should work as you expect, I use a similar approach.

**Comment by johnryan** [comment]
@bpoplauschi that actually wasn't working...ended up having to do this:

in my .pch file so that logs wouldn't get filtered out in the macros.
```
static const int ddLogLevel = DDLogLevelVerbose;
```
then in my app delegate:
```
#ifdef DEBUG
static const int logLevel = DDLogLevelVerbose;
#else
static const int logLevel = DDLogLevelError;
#endif

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    
    [DDLog addLogger:[DDASLLogger sharedInstance] withLevel:logLevel];
    [DDLog addLogger:[DDTTYLogger sharedInstance] withLevel:logLevel];

    self.fileLogger = [[DDFileLogger alloc] init];
    self.fileLogger.rollingFrequency =  60 * 60 * 24; // 1 hour rolling
    self.fileLogger.logFileManager.maximumNumberOfLogFiles = 7;
    self.fileLogger.maximumFileSize = 384 * 1024; // 384K
    [self.fileLogger setLogFormatter:[[DDLogFileFormatterDefault alloc]init]];
    [DDLog addLogger:self.fileLogger withLevel:DDLogLevelVerbose];

    ...
}
```

**Comment by bpoplauschi** [comment]
You can just add this
```
#ifdef DEBUG
static const int logLevel = DDLogLevelVerbose;
#else
static const int logLevel = DDLogLevelError;
#endif
```
to the .pch

**Comment by johnryan** [comment]
@bpoplauschi 
Thats what I originally had, but that created the issue that Release builds wouldn't send DDLogVerbose logs to the file logger as they'd all be filtered out by the LOG_MAYBE macro.

Is that expected?

**Comment by bpoplauschi** [comment]
I think Release builds should not send the verbose logs, so for me is expected. You can decide to change that if you need them.

**Comment by mauron85** [comment]
Ouch, I was just bitten by this. :-) I also would expect that logger level setting will override global level.
