### ISSUE TITLE
Commit 1afb1674159d2adc222e488448e6b1738ed5d0e6 broke ddLogLevel handling?

### ISSUE THREAD

**Issue by afoo** [CocoaLumberjack/CocoaLumberjack#478]
https://github.com/CocoaLumberjack/CocoaLumberjack/commit/1afb1674159d2adc222e488448e6b1738ed5d0e6

How would '#ifdef ddLogLevel' ever be true at compile time if I use a variable?

Either I'm missing something or this keeps ddLogLevel from ever being used in that case.

**Comment by rivera-ernesto** [comment]
I noticed the same thing here: https://github.com/CocoaLumberjack/CocoaLumberjack/pull/473#discussion_r26480615

For now the fix is to `#define LOG_LEVEL_DEF ddLogLevel` before importing CocoaLumberjack.

**Comment by DoctorG** [comment]
Thanks!

**Comment by veegee** [comment]
Wow this is a critical bug. The documentation is so out of sync as well.

Why upgrade to 2.0.0 before thorough testing?

**Comment by rivera-ernesto** [comment]
It is a bug, but not critical, and in the mean time you can follow my advice above to fix it.

I would also put a notice about it in the README.

**Comment by DanSkeel** [comment]
I thought I'm crazy and I can't figure out how to use a well documented super popular logging framework. You should mention this bug in docs.

**Comment by rivera-ernesto** [comment]
It is in the [README](https://github.com/CocoaLumberjack/CocoaLumberjack#migrating-to-2x) but feel free to improve on it.

**Comment by veegee** [comment]
Where exactly is it in the readme?

**Comment by rivera-ernesto** [comment]
Just follow the link.

> ### CocoaLumberjack 2

> #### Migrating to 2.x

> * Replace `DDLog.h` imports by `#import <CocoaLumberjack/CocoaLumberjack.h>`.
* Using `ddLogLevel` to start using the library is now optional. If you define it add `#define LOG_LEVEL_DEF ddLogLevel` before `#import <CocoaLumberjack/CocoaLumberjack.h>` and make change its type to `DDLogLevel`

**Comment by MaddTheSane** [comment]
The read-me is incorrect: the define must be on the command line for now, as the version of Clang included in Xcode 6.3 doesn't allow it to be defined in the source code. This may change in the future, but as it stands, it needs to be on the command line.

**Comment by MaddTheSane** [comment]
This happened when I made the pull request to use modules. One way to get around this is to turn off modules, but this would break Swift support. 

Clang 3.7 added support for the `textual header` keyword, but Xcode 6.3 uses Clang 3.6, which doesn't. The `textual header` would make it so you could `#define LOG_LEVEL_DEF ddLogLevel`, but currently you will need to add `LOG_LEVEL_DEF=ddLogLevel` to your project's preprocessor macros.

Sorry.

**Comment by 0xced** [comment]
The [Dynamic Log Levels documentation](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/DynamicLogLevels.md) is also incomprehensible because of this.

**Comment by rivera-ernesto** [comment]
Most documentation hasn't been updated since 1.9.x.

**Comment by shawnmorrison** [comment]
Adding `LOG_LEVEL_DEF=ddLogLevel` to the Preprocessor Macros does not work for me. I get the same duplicate symbols error others have mentioned even though I'm not defining it elsewhere.

Has anything changed since the above comments?

Is there any documentation for exactly how to set this up correctly?

**Comment by DanSkeel** [comment]
@shawnmorrison hi, It seems like it got fixed in #539. You don't have to define it yourself anymore. May be you get duplicates because you define and assign ddLogLevel in header and include it im multiple source files?

I made [some macros helpers](http://stackoverflow.com/a/29837945/991816) for my self, you can examine my approuch to get the idea of how to use Cocoa Lumberjack properly. (I hope I don't miss anything my self)

The key is to set ddLogLevel in source file, not in header.
If you want a global ddLogLevel you will have to use extern ddLogLevel in some common header.
