### ISSUE TITLE
Manual Install Instructions

### ISSUE THREAD

**Issue by pazzer** [CocoaLumberjack/CocoaLumberjack#564]
I'm struggling to perform a manual install of CocoaLumberjack. After adding the submodule, the docs tell users to ``Drag CocoaLumberjack/Framework/{Desktop/Mobile}/Lumberjack.xcodeproj`` into their project' - but there's no ``Desktop`` folder in the repository - only a mobile one. I tried adding ``Lumberjack.xcodeproj`` instead, but ultimately it fails when I try to define the logging level: 

``static const DDLogLevel ddLogLevel = DDLogLevelVerbose;``

![2015-07-20_23-09-42](https://cloud.githubusercontent.com/assets/3384242/8788456/7b7ff59e-2f32-11e5-9016-78cd276f82b9.png)

What's more, I'm unable to follow the instruction "*Add ``libCocoaLumberjack.a`` to 'Link Binary With Libraries''*" - there's no such file.

**Comment by bpoplauschi** [comment]
I strongly recommend that you install using CocoaPods. Is there a reason you need to add the framework manually?

**Comment by pazzer** [comment]
I've used CocoaLumberjack in conjunction with Cocoapods in the past with no problems, so there's no reason why I *need* to do it manually, I just wanted to give it a try.  Am I right in thinking that the manual install instructions aren't 100% accurate for OS X?

**Comment by bpoplauschi** [comment]
The instructions for manual install might indeed be incorrect. We are strongly advising people to use CocoaPods, as that is the install way we are testing on our end. If you figure out what is missing for the manual install, please make a PR and update that Readme section.

**Comment by rivera-ernesto** [comment]
There are some users that do add it manually using the project file as you can see in the [contributions](https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=project&type=Issues&utf8=✓) made. But the documentation is surely outdated.

Could you try by taking a look at how [RestKit](https://github.com/RestKit/RestKit/wiki/Installing-RestKit-v0.20.x-as-a-Git-Submodule) is manually added and if successful update the docs?

**Comment by miaomi** [comment]
Here is an why:
"
gem install cocoapods --pre
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/cocoapods-0.39.0.beta.4.gemspec.rz)
"
And too slow to use pod command in China. The pod install command often freeze at "Analyzing dependencies" cause of poor network usability. Can you image downloading from GitHub in 7KByte/s with a fiber link says 20Mbps?
(While without an VPN)

**Comment by eliburke** [comment]
As of Xcode 7.1, I am no longer able to use the "Manual" instructions. I've been using 2.0.1 /w Xcode 6 without trouble for months. It appeared to work with Xcode 7 / 7.1, but I suspect now that I had cached build artifacts; I had to remove and re-install Xcode last week, clean and rebuild, and suddenly I was no longer able to Archive an adhoc build. 

I spent quite a few hours trying to fix my project to use the static library, but was never able to get the #include CocoaLumberjack.h to work. Ditto for the framework build, except the problem there was with the @import CocoaLumberjack. 
Using both of these configurations, Running my app worked fine, just not Archiving. 

Eventually I gave up and switched to Carthage. This was fairly painless. I'd like to suggest that you put an even stronger disclaimer in the ReadMe about the Manual instructions being possibly broken.

**Comment by DD-P** [comment]
I use CLJ with manual installation in two OS X Obj-C apps (one ARC, one MRR).  I set my projects up with a separate CocoaLumberjack target (as a dependency) and just copy the .m/.h files from the ./Classes folder.  This is then built as a static library, producing `libCocoaLumberjack.a`.

Currently my .pch file adds:

```
#define LOG_LEVEL_DEF logLevel
#import <CocoaLumberjack/CocoaLumberjack.h>
extern DDLogLevel logLevel;
```

From time-to-time, I manually re-copy and commit updated CLJ files and the build has rarely broken with changes.  I appreciate this is less elegant than the automated solutions with CocoaPods and Carthage.  I am also not using git submodules for this component, but this has worked for me trouble-free since 2011.

Please let me know if this approach helps you @eliburke and I'll see if I can write this up as a PR for consideration, if so.

**Comment by eliburke** [comment]
Yes, I see how that would work, @DD-P . My mistake was being stubborn. Instead of trying anything else, I just kept trying to make it work the way the ReadMe suggested. 

There are a couple of Issues with comments indicating a that the devs don't use or test the Manual instructions much (and in fact I am nearly certain they are wrong for Xcode 7), so I think that info needs to bubble up to https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/GettingStarted.md#manual-installation

**Comment by DD-P** [comment]
Thank you, I'll make a doc PR this weekend for the team to review.

**Comment by DD-P** [comment]
For those interested in this issue, please have a look at #646 and let me know what might need to be added.

**Comment by rivera-ernesto** [comment]
Closing this as the documentation will always keep getting updated (hopefully).
