### ISSUE TITLE
Attach pre-built binaries to release for Carthage

### ISSUE THREAD

**Issue by timshadel** [CocoaLumberjack/CocoaLumberjack#608]
When you release 2.1 and merge Swift 2.0 #588, please also attach the pre-build Carthage libraries to the Github release so they can be downloaded and used directly by Carthage without any local build time required.

Instructions here: https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by ekimia** [comment]
+1

**Comment by sinoru** [comment]
```
carthage build --no-skip-current
carthage archive CocoaLumberjack
carthage archive CocoaLumberjackSwift
```
and attach CocoaLumberjack.framework.zip, CocoaLumberjackSwift.framework.zip
It will be works.

Currently, I don't have any permissions to attach on tag, So I can't do that.

**Comment by bpoplauschi** [comment]
Hopefully you will get the permission soon. Otherwise I will upload the binaries.

**Comment by kballard** [comment]
You'll need to use Carthage 0.9.4 for this (once it's released).

**Comment by bpoplauschi** [comment]
Done. Thanks for the instructions. Check the [2.1.0 tag](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/2.1.0)

**Comment by kballard** [comment]
@bpoplauschi You should regenerate the archive now with Carthage 0.9.4, in order to get the bcsymbolmap files.

**Comment by bpoplauschi** [comment]
@kballard thanks for the suggestion. I added the Carthage 0.9.4 binaries along with the 0.9.3 ones. For future version, I will only add 0.9.4 ones. See the updated tag [2.1.0](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/2.1.0)

**Comment by ikesyo** [comment]
@bpoplauschi Related to

> and attach CocoaLumberjack.framework.zip, CocoaLumberjackSwift.framework.zip to tag release.
It will be works.

and

> @kballard thanks for the suggestion. I added the Carthage 0.9.4 binaries along with the 0.9.3 ones. For future version, I will only add 0.9.4 ones. See the updated tag 2.1.0

attaching multiple framework zip files does not work. Carthage would use the first one of the assets inclueded in a release. At the case of 2.1.0, `CocoaLumberjack.framework_Carthage_0_9_3.zip` is the one.

**Comment by bpoplauschi** [comment]
@ikesyo I did not know that, thanks. I removed the 0.9.3 zips and also added the binaries for version 2.2.0 which I forgot to do earlier.

**Comment by eskerber** [comment]
@bpoplauschi May i politely suggest re-opening this issue and reverting the change? By using prebuilt frameworks written in Swift, each release is tied to a version of Xcode. 

For instance, if I point to:

```ruby
github "CocoaLumberjack/CocoaLumberjack" "2.2.0"
```
Then instead of building from source with Xcode 7.3, carthage downloads the binaries using Xcode 7.1. The end result of that, of course, is this type of build error.

![screen shot 2016-03-23 at 3 17 30 pm](https://cloud.githubusercontent.com/assets/75236/13999485/7e7a31d4-f10a-11e5-85d6-b20df84aa7a8.png)

Prebuilt binaries are :+1: for Objective-C, or Swift once we reach ABI stability. For now, they require new releases or for us to point directly to a commit SHA to get around the prebuilt binaries.

Thoughts?

**Comment by kballard** [comment]
I agree with @eskerber, pre-built binaries are not appropriate for any framework that contains Swift code (until such time as the Swift ABI stabilizes). As an end-user with Carthage, the only solution I have to this problem while still depending on a release (instead of on a sha / branch) is to pass the `--no-use-binaries` flag to `carthage checkout`/`carthage bootstrap`, and that disables binaries for *all* dependencies.

**Comment by ikesyo** [comment]
> As an end-user with Carthage, the only solution I have to this problem while still depending on a release (instead of on a sha / branch) is to pass the `--no-use-binaries` flag to `carthage checkout/carthage bootstrap`, and that disables binaries for all dependencies.

Or specifying a commit hash (8c8d155 for 2.2.0) would work around too.

**Comment by kballard** [comment]
That's the sha that I mentioned. The problem with doing that is upgrading then becomes a very manual process, whereas if you depend on a release then you can use semantic versioning.

**Comment by ikesyo** [comment]
Oh, I overlooked that, sorry. :bow:

**Comment by bpoplauschi** [comment]
You guys are right, I will take care of this this week. Thanks for properly describing the situation

**Comment by rivera-ernesto** [comment]
I also believe that it is not a good idea to distribute compiled Swift code as the binaries are not backwards (or forward!) compatibles with other Swift/Xcode versions. Reason explained by Apple as well.

Moreover there is a command in Carthage to use source code instead of binaries which could be added to the README instead. This will also make easier for maintainers and prevent weird bugs from users.

**Comment by bpoplauschi** [comment]
I removed both the Swift and Obj-C binaries. I wasn't sure about the Obj-C ones, but I figured Obj-C users can still pull everything from sources, so it should be ok. Right?
