### ISSUE TITLE
Carthage not generating CocoaLumberjack-Swift framework ? 

### ISSUE THREAD

**Issue by kyro38** [CocoaLumberjack/CocoaLumberjack#666]
After a `carthage update` there are only `CocoaLumberjack.framework` in the directories and no `CocoaLumberjack-Swift.framework`. 

There is either a problem or the documentation is not compete enough to generate the swift frameworks.

**Comment by rivera-ernesto** [comment]
I think documentation is not updated to reflect #647.

**Comment by kyro38** [comment]
My cartfile.resolved contains
`github "CocoaLumberjack/CocoaLumberjack" "2.2.0"`
Does this still apply ? 

Also, what do I need to do to make the framework work on my project since there is no `CocoaLumberjackSwift` and currently the methods defined in `CocoaLumberjack.swift` are not accessible. (Or methods are though)

**Comment by sushichop** [comment]
It seems that there are several reasons...

In release [2.2.0](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/2.2.0), there are TWO zip files for framework. As far as I read [Carthage README](https://github.com/Carthage/Carthage/blob/master/README.md), I think it should be archived to ONE zip. 
Actually I could get CocoaLumberjack.framework, but not CocoaLumberjackSwift.framework with
```bash
$ carthage update
```

In order to get ALL frameworks(CocoaLumberjack.framework and CocoaLumberjackSwift.framework), I needed to use with "no-use-binaries" option. This option means that you build frameworks at your local(disable downloading pre-build framework file).
```bash
$ carthage update --no-use-binaries
```
And then I imported CocoaLumberjackSwift.framework to the source code.

**Comment by sushichop** [comment]
Additional info.
As suspected unfortunately, Carthage would use the only first one of the assets inclueded in a release as @ikesyo said(https://github.com/CocoaLumberjack/CocoaLumberjack/issues/608).


> github "CocoaLumberjack/CocoaLumberjack" "2.2.0"
> Does this still apply ?

@kyro38 
I think yes. But you need  work-around  in 2.2.0 by the reason stated above
I could use CocoaLumbarjack 2.2.0 with Carthage by the following way.
And Carthage version is 0.11.0 in my environment.

1)  build frameworks at your local
```
$ carthage update --no-use-binaries
```

2) add both CocoaLumberjack.framework and CocoaLumberjackSwift.framework to "Linked Frameworks and Libraries"

3) add Run Script(probably this will be as same as you usually use Carthage )
[shell]
/usr/local/bin/carthage copy-frameworks
[Input Files]
$(SRCROOT)/Carthage/Build/iOS/CocoaLumberjack.framework 
$(SRCROOT)/Carthage/Build/iOS/CocoaLumberjackSwift.framework

4) import CocoaLumberjackSwift in your source code

I hope this will help you.

**Comment by fatuhoku** [comment]
Another way to get things rolling is to point Carthage at the `master` branch:

`github "CocoaLumberjack/CocoaLumberjack" "master"`
Then `$ carthage update CocoaLumberjack --platform iOS`
Then you'll find that both *Swift and non-Swift frameworks are built (don't ask me why).
Then `import CocoaLumberjackSwift` instead of the usual `import CocoaLumberjack`

**Comment by ikesyo** [comment]
As of Carthage 0.12, you can easily archive multiple frameworks into one zip file by `carthage archive CocoaLumberjack CocoaLumberjackSwift` or just `carthage archive` (the latter would find the frameworks comes from the current project). Attaching the single zip file to your releases should fix the issue.

@bpoplauschi @rivera-ernesto

**Comment by bpoplauschi** [comment]
Please see #608, we have decided not to attach pre-built binaries to our releases. I think you guys can use the standard approach and have the library built on your machines by Carthage.
