### ISSUE TITLE
Can CocoaLumberjack make device fever with frequent IO?

### ISSUE THREAD

**Issue by talisk** [CocoaLumberjack/CocoaLumberjack#722]
I will log all of the requests into a file, and upload files at the proper time.

The frequent internet request will take plenty of logs, and the frequent IO will make device fever.

I shouldn't make a L2 cache for the log, because It should loss some log when the App crashed.

Does CocoaLumberjack optimize performance in this case?

**Comment by rivera-ernesto** [comment]
I am not sure about file log performance.

**Comment by carllindberg** [comment]
DDFileLogger performance could be improved by using DDTTYLogger's approach to adding a newline on log messages which need them -- right now it creates a copy of the string every time.

CocoaLumberjack 2.0 however probably performs much much worse in high-workload situations, due to its creating lots more temporary NSStrings etc. instead of passing constant C-strings down to the formatters (changes in DDLogMessage API; old version was more optimized for performance, new version more for ease of use).  1.x might work better if you really have a lot of logs.  But, there will always be a limit to how much you can do before file I/O becomes a significant part of your program time.

**Comment by bpoplauschi** [comment]
Old discussion. Closing. Feel free to create a new issue to talk about those performance aspects if you think it's appropriate.
