### ISSUE TITLE
The main thread Hang

### ISSUE THREAD

**Issue by rooboios** [CocoaLumberjack/CocoaLumberjack#812]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.1.1
 CocoaLumberjack Version | 3.0.0
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 8.1

### The main thread Hang

![2016-12-01 5 33 45](https://cloud.githubusercontent.com/assets/23630005/20789080/2758eeee-b7ee-11e6-9709-e8a0327453bb.png)
![2016-12-01 5 33 56](https://cloud.githubusercontent.com/assets/23630005/20789084/29f13bfc-b7ee-11e6-9a32-8e0b9425b2c1.png)

**Comment by mcmengchen** [comment]
I have the save problem.

**Comment by guidedways** [comment]
Same here! I kept pulling my hair out till I realised it's Cocoalumberjack causing this. Any fix?

**Comment by bpoplauschi** [comment]
We should investigate and fix, this sounds like a real problem.

@rooboios @mcmengchen @guidedways are you logging errors in that case? Because for errors, we are logging synchronously and that might somehow cause a deadlock.

CC @rivera-ernesto

**Comment by guidedways** [comment]
Yup, was logging errors. I had to change it in a fork to not use the main thread (although the problem was elsewhere in our code that kept hammering the main thread, it was however cocoalumberjack that caused a deadlock).

**Comment by bpoplauschi** [comment]
@guidedways Any suggestions on how we can fix this in CocoaLumberjack?

**Comment by guidedways** [comment]
@bpoplauschi I'm not a 100% sure but clearly the deadlock is there on the locks used by the dispatch queue, and so if we were simply to by pass using `dispatch_sync`, we would solve the problem. `dispatch_sync` is known to cause dead-locks (for instance calling it on the main queue from code executing on the main queue would cause it to hold the lock indefinitely). 

The issue is here in `DDLog.m`:

```ObjC
    if (asyncFlag) {
        dispatch_async(_loggingQueue, logBlock);
    } else {
        dispatch_sync(_loggingQueue, logBlock); <--- causing the deadlock
    }
```

Clearly, two background threads throwing an error at the same time is causing it to dead-lock (since they're both calling `dispatch_sync` on the same queue at the same time). And this is possibly what's happening in our case since we have several background worker threads, and two or three may at a given time try and `DDLogError(...)` at the same time. 

I should suggest we add the following method:

```ObjC
- (BOOL) isOnLoggingQueue {
  static const void* loggingQueueKey = @"loggingQueue";
  static void* loggingQueueContext = @"loggingQueue";
  
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{   
    dispatch_queue_set_specific(_loggingQueue, loggingQueueKey, loggingQueueContext, nil);    
  });
  return dispatch_get_specific(loggingQueueKey) == loggingQueueContext;
}
```

And change the code to:

```ObjC
    if (asyncFlag) {
        dispatch_async(_loggingQueue, logBlock);
    } else {
       if ([self isOnLoggingQueue]) {
            logBlock();
       } else {
            dispatch_sync(_loggingQueue, logBlock);
       }
    }
```

That should hopefully fix it.

**Comment by tar500** [comment]
looks like it's related to #689
any update on this?

**Comment by hhanesand** [comment]
@guidedways The change you have proposed won't do anything. If we are on `_loggingQueue` calling `dispatch_sync(_loggingQueue, logBlock)` is functionally equivalent to calling `logBlock()`. (not discounting the fact that it is an issue)

**Comment by hhanesand** [comment]
@rooboios @guidedways @mcmengchen @tar500 Can any of you reproduce this issue on the master branch? If you're able to, we'd love to see a backtrace from all threads, (via `bt all`).

**Comment by hhanesand** [comment]
Closing due to no response. Please open a new issue with a full backtrace if you can reproduce this on version 3.5.0 or later.
