### ISSUE TITLE
Use pod_target_xcconfig instead of xcconfig in the podspec

### ISSUE THREAD

**Issue by benasher44** [CocoaLumberjack/CocoaLumberjack#814]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

Xcode 8.x
CocoaPods 1.1.x

### Issue Description and Steps

Hi there! In CocoaPods/CocoaPods#5952, some people claimed that CocoaPods is warning about Xcode overriding CocoaPods's `SWIFT_VERSION` setting in their projects. The versions of CocoaPods that are more Swift-aware (1.1.x) do not set `SWIFT_VERSION` in the user's project, but we noticed that CocoaLumberjack does via the [`xcconfig` podspec attribute](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/CocoaLumberjack.podspec#L52). This is actually an older attribute, and it's preferred to just replace that with `pod_target_xcconfig` instead. This ensures that CocoaLumberjack itself is built with the settings that you all prefer, and then the user's project's settings remain untouched.

In the context of this particular project, using `pod_target_xcconfig` should work just fine because if a user tries to integrate CocoaLumberjack into a project with a conflicting Swift version, Xcode will produce an error at build time saying so.

I'd be happy to open a PR making this short change. Thanks!

**Comment by sushichop** [comment]
@benasher44 

Thank you for your comment. I agree with you.
Now, using post_install hook is a common and preferred way to integrate CocoaPods with Xcode 8.0+.

Just a minute ago I pushed PR that supports both Swift 3.0 and Swift 3.0.1. #816 
And it also let developers integrate CocoaPods as they prefer.
The related commit is [here](https://github.com/CocoaLumberjack/CocoaLumberjack/pull/816/commits/3069fcf2bf2ddbf1f9edf76d6ef05efdcdd329e1).

Thanks.

**Comment by raksik** [comment]
@sushichop 
Can you please create a new tag (e.g. 3.0.1) with this change? https://github.com/CocoaLumberjack/CocoaLumberjack/pull/816/commits/3069fcf2bf2ddbf1f9edf76d6ef05efdcdd329e1
The relevant issue keeps us from integrating our project written in Swift3.0 with Cocoalumberjack.

**Comment by sushichop** [comment]
@raksik 
Probably I think you need ask @bpoplauschi or @rivera-ernesto to release a new version.
Or you can use master branch. My comment in #821 will be helpfule for you.

@bpoplauschi @rivera-ernesto
Do you have a plan to release a new version at an early date?
If you do so, I'd like to make some pull requests before the fact.
Actually I removed `xcconfig attribute` from podspec, but I don't add `pod_target_xcconfig attribute` **yet** because IMHO Xcode 8.1 is a little odd.

 Xocode  | Toolchain    | SWIFT_VERSION in build settings|
 --------|--------------|--------------------------------|
 8.0     | Swift 3.0    | 3.0                            |
 8.1     | Swift 3.0.1  | 3.0.1                          |
 8.2     | Swift 3.0.2  | 3.0                            |

So if you use/support `pod_target_xcconfig attribute`, IMHO it had better be together with the travis xcode 8.2 image. 
[Note]
Now CocoaLumberjack master branch works well w/o `pod_target_xcconfig attribute`, however, `pod_target_xcconfig attribute` is kindly for users. 

If you use travis xcode 8.2 image, I know a trivial workaround is still needed. See https://github.com/travis-ci/travis-ci/issues/7031 for details.
Could I make an PR to do this?

**Comment by benasher44** [comment]
Generally, I'd say it's better to ship without a `SWIFT_VERSION` setting in the podspec. CocoaPods already sets this in the pod targets to the setting that is set in the user's main project. This way, you lean on Xcode to ensure the setting is correct for the user's project and Xcode version. If the setting is wrong, Xcode will warn the user about it, and then they can change it in their project without requiring a PR here.

**Comment by sushichop** [comment]
@benasher44 
Thank you for your advice again. I understand CocoaLumberjack doesn't need a `SWIFT_VERSION` setting in the podspec anymore. Your explanation makes sense!

**Comment by benasher44** [comment]
Great! I'm going to close this then. It would be nice to see a new release though! Thanks again for your help!
