### ISSUE TITLE
iOS 10.3 - ASL Depreciation warnings

### ISSUE THREAD

**Issue by tylerjnettleton** [CocoaLumberjack/CocoaLumberjack#858]
Just upgraded to the latest xcode for iOS 10.3 and noticed warnings saying ASL is now deprecated as of 10.3. Are there any plans to replace ASL calls with the new OS logging methods?

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Xcode Version           | e.g. Xcode 10.3

**Comment by chrismcs** [comment]
fwiw - the same ASL deprecation warnings show up in watchOS 3 as well

**Comment by sushichop** [comment]
I recommend you use `DDOSLogger` instead of `DDASLLogger` with iOS 10+, macOS 10.12+, tvOS 10.0+, and watchOS 3.0+. You can use it from CocoaLumberjack 3.2.0.

And `DDOSLogger` uses `<os/log.h>` that comes from a new OS logging system. If you are interested in it,  see [here](https://developer.apple.com/reference/os/os_log).

**Comment by ripperhe** [comment]
os_log replacement for asl_search? Does anyone know of a way to read the printed log using the new os_log api?
