### ISSUE TITLE
Turn of "sharing" of all schemes

### ISSUE THREAD

**Issue by insha** [CocoaLumberjack/CocoaLumberjack#881]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name                | iOS
 Platform Version             | 9 to 10.x
 CocoaLumberjack Version | 3.0.0
 Integration Method |  Manually
 Xcode Version | 8.3.3

### Issue Description and Steps

Is it possible to have the "sharing" of all schemes turned off by default? This is polluting the scheme popup menu in Xcode, because in the project where we use CocoaLumberjack, there is no need to see these schemes. I do know that I can turn off the schemes on a per user basis, but I need to do it for the whole team.

**Comment by bpoplauschi** [comment]
@insha I don't think there is an option that we can disable. As @sushichop said, we do share a lot of schemes due to Carthage needing those, so that is why they appear in your Xcode project (due to the fact that you are integrating manually). 

We should dig a bit, see what options do we have.
Please note we usually focused on the CocoaPods and Carthage install methods, in which this problem would not exist. But this doesn't mean we are ignoring the issue for manual installation.

Any ideas?

**Comment by sushichop** [comment]
> because in the project where we use CocoaLumberjack, there is no need to see these schemes. I do know that I can turn off the schemes on a per user basis, but I need to do it for the whole team.

Do you and your team use `CocoaLumberjack` as git sub module in order to share your developing projects?

As you know probably, `xcshareddata/xcschmes/*.xcscheme` are used for sharing schemes.
If you or one of your team add `xcshareddata/xcschmes/*.xcscheme` to gitignore file, I think whole team does not need to do the same things.

I'm not sure, can you achieve your purpose by above method?

**Comment by bpoplauschi** [comment]
@sushichop the idea is good, but I think it will ignore all the Xcode schemes, including the ones they need. An improved filtering should be used, maybe directly on the CocoaLumberjack path to ignore only our schemes.
Maybe this was your idea all along and I din't understand it :)

**Comment by sushichop** [comment]
> As you know probably, xcshareddata/xcschmes/*.xcscheme are used for sharing schemes.
> If you or one of your team add xcshareddata/xcschmes/*.xcscheme to gitignore file, I think whole team does not need to do the same things.

Sorry I made a typo.
NOT correct: xcshareddata/xcschmes/*.xcscheme to gitignore file
correct: Lumberjack.xcodeproj/xcshareddata/xcschmes/CocoaLumberjack*.xcscheme to gitignore file

I suppose that developers can add gitignore settings in their project, 
but this may not be an ideal solution.

**Comment by bpoplauschi** [comment]
I agree it's not ideal, but it's better than us removing all the schemes needed for Carthage - I think

**Comment by insha** [comment]
@sushichop Thank you. We do use CocoaLumberjack as a submodule and using Carthage/CocoaPods are not an option. I will try ignoring the schemes using `.gitignore` as you suggest.

**Comment by sushichop** [comment]
I'm going to close this issue based on the last comments.
Please feel free to reopen it if you have still any issue.
