### ISSUE TITLE
Xcode 9 warnings fix

### ISSUE THREAD

**Issue by ivulyov90** [CocoaLumberjack/CocoaLumberjack#898]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        | 11.0
 CocoaLumberjack Version | 3.3.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.0.1
 Repro rate              | all the time (100%)

### Issue Description and Steps

There is one warning in Xcode 9
Pods/CocoaLumberjack/Classes/DDOSLogger.m:19:8: 'DDOSLogger' is partial: introduced in iOS 10.0
Pods/CocoaLumberjack/Classes/DDOSLogger.m:19:20: Annotate 'sharedInstance' with an availability attribute to silence

It will be nice to fix it.

**Comment by sushichop** [comment]
@ivulyov90 
Thanks for your opening issue. 
This issue should be fixed by https://github.com/CocoaLumberjack/CocoaLumberjack/pull/895 that includes some other fixes. See [this commit](https://github.com/CocoaLumberjack/CocoaLumberjack/commit/6c810bfb82182fbcb2b9e2f769ae490ea506f061) to be more precise.

As you see, https://github.com/CocoaLumberjack/CocoaLumberjack/pull/895 has been already merged to master branch, but not released yet. I think it probably will come together with CocoaLumberjack `3.4.0`.

**Comment by guykogus** [comment]
Hey, any update on when `3.4.0` will be released? This warning has been nagging me for some time 😛

**Comment by svendr** [comment]
Yeah I'm also patiently waiting to get a fix for this warning :)

**Comment by sushichop** [comment]
Hi guys, [`CocoaLumberjack 3.4.0`](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.4.0) has been released!

@ivulyov90
Can you close this issue if you confirm it is solved?

@rivera-ernesto 
Thanks for your release!

**Comment by rivera-ernesto** [comment]
Thank you all for the contributions. Keep them coming and I'll try to make releases more often.

Cheers

**Comment by ivulyov90** [comment]
@rivera-ernesto Thanks! 👍
