### ISSUE TITLE
[QUESTION] Using two separate instance of cocoaLumberjack in both sdk and App

### ISSUE THREAD

**Issue by aasawa99** [CocoaLumberjack/CocoaLumberjack#980]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
* [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  9.0
 CocoaLumberjack Version | e.g. 3.4.2
 Integration Method      |  cocoapods / manually
 Xcode Version           |  Xcode 10
 Repro rate              | e.g. all the time (100%)
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Hi,
I have written SDK (let say MySDK), where have added lumberjack SDK manually. And its working fine. Now, I am working on the app, where I have added  MySDK, and another SDK using pod file, and that another SDK uses lumberjack, and I am start receiving following errors on console, when I run the test app.

```
Class DDAbstractDatabaseLogger is implemented in both 
~TestApp.app/Frameworks/MySDK.framework/HyperTrackCore (0x1016f5e48) and 
~TestApp.app/Frameworks/CocoaLumberjack.framework/CocoaLumberjack (0x100f81d30). 
One of the two will be used. Which one is undefined.
```

The reason I didnt used, lumberjack sdk using pod file in my own sdk, is because I want to have my own separate log files which doesnt get mix with host app.

Any ideas how can I solve this problem.

**Comment by bpoplauschi** [comment]
@aasawa99 Thanks for getting back to us.
First of all, the problem here is you have duplicated the `CocoaLumberjack` symbols by having two copies of the files.
This is not a blocking issue, as the app compiles and runs, but problems can occur since which one of the classes will get used is random. This is for the case where the 2 hardcopies are of the exact same version of the framework. If the versions are different, even bigger problems can happen (i.e. crashes or logical errors).
From my points of view, there are a few options to solve this:
- recommended option: use a dependency manager (like CocoaPods or Carthage). Then make explicit that `MySDK` depends on `CocoaLumberjack` without hard-copying its files inside `MySDK`. Then the app will use that dependency manager to bring all the correct dependencies and build them
- no dependency managers policy: if you don't want to do the previous, you can just embed `CocoaLumberjack` into `MySDK` as you already have. Then don't include it into your app, just use the one from `MySDK` (header files need to be public).

Take a look at https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/CustomContext.md, it contains some details about Contexts that were designed to allow separation of context based on the module (so basically `MySDK` logs will have a different context than the ones from the  app). Also, the link refers to [CocoaHTTPServer](
https://github.com/robbiehanson/CocoaHTTPServer) - a framework that depends on `CocoaLumberjack`

**Comment by aasawa99** [comment]
Ok, got it. I decided to use using dependency manager, CocoaPods. My motivation to do that separately was to have separate log files specific to MySDK only. Is there is a way I can achieve same, because if host app also uses lumberjack, then it ends up sharing the same log file for MySDK and host app.

**Comment by lolgear** [comment]
@aasawa99 
Yes, you can, but without CocoaLumberjack. OS logging is your friend.
I suggest you to spend time and watch video. [Unified Logging and Activity Tracing](https://developer.apple.com/videos/play/wwdc2016/721/)

In a nutshell, CocoaLumberjack doesn't have nice easy-to-setup mechanism to separate logs from different targets.
This problem was solved by Apple in `os logging`. Don't be mystified that `DDOSLogger` do the same.

**Comment by bpoplauschi** [comment]
There could be some options to having separate log files, I think.
If you would create one instance of `DDFileLogger` from `MySDK` and another from your app, each one with a different file path. Creating a custom `LogFormatter` implementation that, depending on `context` (is available from a `DDLogMessage`), can send the logs to one file logger or the other.
Just an idea

**Comment by hhanesand** [comment]
I release a closed source SDK in which CocoaLumberjack is used. I've included the files, and performed a rename from the DD prefix to my own prefix. Works just fine, clients can include their own copy of CocoaLumberjack. Only thing you have to modify is probably the log file location to avoid 2 instances of CL writing to the same log folder.
